### ISSUE TITLE
Error when trying to run the eurostat example

### ISSUE THREAD

**Issue by joshuabezaleel** [oeg-upm/rmlc-statistic#21]
Hi RMLC-Statistic team,

I am trying to run the example mentioned at the homepage of this repo which is
`java -jar target/rmlc-statistic-1.0.jar -m examples/eurostat/eurostatimmigration-columns.rmlc.ttl -c examples/eurostat/eurostatimmigration.csv -q examples/eurostat/eurostatimmigration-query1.rq`

and I got this error
![image](https://user-images.githubusercontent.com/7043511/43620194-b91d760e-96fb-11e8-82e5-180454145fc8.png)

Is there anything that I did wrong? And how do I resolve this error?

Thank you very much. Best regards to all RMLC-Statistic team.

**Comment by dachafra** [comment]
Hi,
The problem was with the use of different Jena versions in morph-rdb and rmlc-statistics. Now it is solved and works. Thank you to be interested in rmlc.

Bests
